import type { CSSProperties } from 'react';
import Link from 'next/link';
import BrandMark from '../components/BrandMark';
import CommercialLeadForm from '../components/CommercialLeadForm';

const modules = [
  ['01', 'Inbox', 'Conversas, filas e responsáveis no mesmo espaço.'],
  ['02', 'Automação', 'Menus, condições e direcionamentos construídos visualmente.'],
  ['03', 'Clientes', 'Contatos, empresas e histórico conectados ao atendimento.'],
  ['04', 'Serviços', 'Ordens, equipamentos, etapas e painel operacional.'],
  ['05', 'Agenda', 'Compromissos ligados ao cliente e à conversa.'],
  ['06', 'Gestão', 'Permissões, auditoria e visão da operação em tempo real.'],
];
const faq = [
  ['A Syrum funciona com WhatsApp?', 'Sim. A plataforma centraliza atendimentos do WhatsApp e organiza cada conversa entre filas, departamentos e responsáveis conforme a configuração da empresa.'],
  ['É possível criar fluxos de atendimento?', 'Sim. O editor visual permite combinar mensagens, menus, condições, filas, responsáveis, esperas e encerramentos para adaptar o atendimento à operação.'],
  ['A plataforma serve apenas para vendas?', 'Não. A Syrum conecta relacionamento, suporte, agenda e ordens de serviço. A estrutura pode acompanhar tanto uma oportunidade quanto um atendimento técnico completo.'],
  ['Como acontece a implantação?', 'A configuração começa pela estrutura da empresa: usuários, departamentos, filas, canais e horários. Depois, os fluxos são ajustados e a equipe inicia a operação acompanhada.'],
];
function Arrow() { return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h13m-5-5 5 5-5 5" /></svg>; }
function Check() { return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4 10-10" /></svg>; }

function ProductStage() {
  const conversations = [['FM','Fernanda Moriguti','Preciso de ajuda com meu pedido','Atendendo'],['CT','Conrat Tecnologia','Arquivo recebido','Na fila'],['BM','Bem Mais Autopeças','Orçamento aprovado','Serviços'],['JP','João Pedro','Obrigado pelo atendimento','Encerrado']];
  return <div className="sy-product-stage" aria-label="Prévia visual da central operacional Syrum"><div className="sy-product-top"><BrandMark variant="symbol" /><span>Central operacional</span><i/><small>Operação sincronizada</small></div><div className="sy-product-body"><aside><b>SY</b>{['▥','□','◇','⌁','≋'].map((icon,index)=><span className={index===1?'active':''} key={icon}>{icon}</span>)}</aside><section className="sy-product-list"><header><strong>Inbox</strong><button>＋</button></header><label>⌕ &nbsp; Buscar conversa...</label>{conversations.map((item,index)=><article className={index===0?'selected':''} key={item[1]}><i>{item[0]}</i><div><strong>{item[1]}</strong><p>{item[2]}</p><small>WhatsApp · {item[3]}</small></div><time>{index===0?'agora':'11:24'}</time></article>)}</section><section className="sy-product-chat"><header><i>FM</i><div><strong>Fernanda Moriguti</strong><small>WhatsApp · Fila Assistência · Responsável Gabriel</small></div><button>Transferir</button></header><div className="sy-chat-space"><span className="incoming">Olá, preciso de ajuda com meu equipamento.<small>11:21</small></span><em>Atendimento direcionado para Assistência</em><span className="outgoing"><b>Gabriel:</b> Boa tarde, Fernanda. Vou dar continuidade ao seu atendimento.<small>11:22</small></span></div><footer>⌕ &nbsp; Digite uma mensagem <button>➤</button></footer></section></div></div>;
}
function FlowVisual() { return <div className="sy-flow-visual"><div className="flow-grid"/><div className="flow-node start"><small>INÍCIO</small><strong>Mensagem recebida</strong><span>WhatsApp</span></div><div className="flow-line one"/><div className="flow-node menu"><small>MENU</small><strong>Como podemos ajudar?</strong><span>Suporte · Financeiro · Serviços</span></div><div className="flow-line two"/><div className="flow-node queue"><small>DIRECIONAMENTO</small><strong>Mover para fila</strong><span>Equipe responsável</span></div><div className="flow-cursor">↗</div></div>; }
function ServiceVisual() { const columns: Array<[string, string[]]>=[['Entrada / Recebido',['OS #000018 · Notebook','OS #000019 · Impressora']],['Em análise',['OS #000016 · Computador']],['Serviço em andamento',['OS #000014 · Manutenção']],['Serviço concluído',['OS #000012 · Instalação']]]; return <div className="sy-service-visual"><header><span>PAINEL DE SERVIÇOS</span><b>Operação ao vivo</b></header><div className="service-columns">{columns.map((column,index)=><section key={column[0]}><h4><i style={{'--dot':`var(--step-${index})`} as CSSProperties}/>{column[0]}</h4>{column[1].map(card=><article key={card}><small>{card.split(' · ')[0]}</small><strong>{card.split(' · ')[1]}</strong><span>{index===3?'Pronto para entrega':'Atualizado agora'}</span></article>)}</section>)}</div></div>; }

export default function SyrumLanding({ className }: { className: string }) {
  return <div className={`sy-site ${className}`}><header className="sy-header"><Link href="#inicio" aria-label="Syrum, início"><BrandMark/></Link><nav><a href="#plataforma">Plataforma</a><a href="#como-funciona">Como funciona</a><a href="#servicos">Serviços</a><a href="#implantacao">Implantação</a></nav><div><Link href="https://app.syrum.com.br/login">Entrar</Link><a className="sy-button small" href="#demonstracao">Conhecer a Syrum <Arrow/></a></div></header><main>
    <section className="sy-hero" id="inicio"><div className="sy-orbit orbit-one"/><div className="sy-orbit orbit-two"/><div className="sy-hero-copy"><span className="sy-kicker"><i/> Uma operação, um lugar</span><h1>A central operacional<br/>da sua <em>empresa.</em></h1><p>WhatsApp, clientes, equipe, automação e serviços trabalhando juntos — do primeiro contato à entrega.</p><div className="sy-actions"><a className="sy-button" href="#demonstracao">Solicitar apresentação <Arrow/></a><a className="sy-text-link" href="#plataforma">Explorar a plataforma ↓</a></div></div><ProductStage/><div className="sy-hero-foot"><span>Atendimento</span><i/><span>Automação</span><i/><span>Relacionamento</span><i/><span>Serviços</span></div></section>
    <section className="sy-manifest"><p>Quando a operação fica espalhada, o contexto desaparece.</p><h2>A Syrum conecta a conversa ao trabalho que precisa acontecer depois dela.</h2></section>
    <section className="sy-journey" id="como-funciona"><header><span className="sy-kicker">DA MENSAGEM À OPERAÇÃO</span><h2>O atendimento não termina<br/>quando a conversa acaba.</h2></header><div className="sy-journey-track">{[['01','Cliente chama','A conversa entra pelo canal configurado.'],['02','Syrum organiza','O fluxo identifica, direciona e registra.'],['03','Equipe assume','O responsável recebe contexto para continuar.'],['04','Operação avança','Agenda, serviço ou acompanhamento seguem conectados.']].map((step,index)=><article key={step[0]}><span>{step[0]}</span><div><h3>{step[1]}</h3><p>{step[2]}</p></div>{index<3&&<i>→</i>}</article>)}</div></section>
    <section className="sy-platform" id="plataforma"><div className="sy-platform-copy"><span className="sy-kicker">PLATAFORMA MODULAR</span><h2>Uma base única.<br/>Diferentes formas de operar.</h2><p>Ative os módulos que fazem sentido para a empresa e mantenha pessoas, conversas e processos ligados ao mesmo contexto.</p><a href="#demonstracao" className="sy-text-link">Ver a Syrum em funcionamento <Arrow/></a></div><div className="sy-module-grid">{modules.map(module=><article key={module[0]}><span>{module[0]}</span><h3>{module[1]}</h3><p>{module[2]}</p><i>↗</i></article>)}</div></section>
    <section className="sy-feature sy-feature-inbox"><div className="sy-feature-copy"><span className="sy-kicker">INBOX COMPARTILHADO</span><h2>Uma conversa inteira.<br/>Mesmo quando a equipe muda.</h2><p>Cada mensagem chega com canal, fila e responsável visíveis. Transferências preservam o histórico e deixam claro quem está conduzindo o atendimento.</p><ul><li><Check/>Filas e departamentos</li><li><Check/>Transferência entre responsáveis</li><li><Check/>Histórico conectado ao cliente</li></ul></div><div className="sy-inbox-detail"><div className="inbox-person"><i>FM</i><div><strong>Fernanda Moriguti</strong><small>WhatsApp · Assistência</small></div><span>Em atendimento</span></div><div className="inbox-dialog"><p>Meu equipamento apresentou o mesmo problema.</p><em>Conversa direcionada para Assistência</em><p className="reply"><b>Gabriel:</b> Vou conferir o histórico e dar continuidade.</p></div><div className="inbox-compose">Digite uma mensagem… <b>➤</b></div></div></section>
    <section className="sy-feature sy-feature-flow"><FlowVisual/><div className="sy-feature-copy"><span className="sy-kicker">AUTOMAÇÃO VISUAL</span><h2>Desenhe o caminho.<br/>A Syrum conduz.</h2><p>Monte menus de atendimento, condições e direcionamentos sem esconder a lógica da operação. A equipe enxerga o fluxo e pode intervir quando necessário.</p><ul><li><Check/>Menus clicáveis e resposta numérica</li><li><Check/>Horários e mensagens de ausência</li><li><Check/>Direcionamento para filas e usuários</li></ul></div></section>
    <section className="sy-services" id="servicos"><header><div><span className="sy-kicker">ORDENS DE SERVIÇO</span><h2>Da entrada à entrega,<br/>sem perder o cliente de vista.</h2></div><p>Atendimento, equipamento, orçamento, execução e entrega avançam no mesmo ambiente. O painel deixa a operação legível para quem executa e para quem gerencia.</p></header><ServiceVisual/></section>
    <section className="sy-bridge"><div><span className="sy-kicker">TRABALHE COM O QUE JÁ EXISTE</span><h2>A Syrum centraliza.<br/>Não obriga sua empresa a começar do zero.</h2></div><div className="sy-bridge-card"><span>APLICATIVOS EXTERNOS</span><h3>Se outro sistema faz parte da rotina, ele pode continuar por perto.</h3><p>Cadastre plataformas externas e acesse-as dentro da central operacional, alternando entre atendimento e sistema sem espalhar janelas pela operação.</p><div><b>SYRUM</b><i>＋</i><b>SEU SISTEMA</b></div></div></section>
    <section className="sy-implementation" id="implantacao"><header><span className="sy-kicker">IMPLANTAÇÃO ORIENTADA À OPERAÇÃO</span><h2>Primeiro entendemos o trabalho.<br/>Depois configuramos a tecnologia.</h2></header><div>{[['Mapear','Estrutura, canais, equipes e rotina atual.'],['Organizar','Departamentos, filas, permissões e horários.'],['Construir','Fluxos, automações e módulos necessários.'],['Operar','Entrada da equipe com acompanhamento e ajustes.']].map((item,index)=><article key={item[0]}><span>0{index+1}</span><h3>{item[0]}</h3><p>{item[1]}</p></article>)}</div></section>
    <section className="sy-demo" id="demonstracao"><div className="sy-demo-copy"><span className="sy-kicker">CONHEÇA A SYRUM</span><h2>Mostre como sua empresa trabalha hoje.</h2><p>A apresentação começa pela sua operação. Assim conseguimos mostrar como a Syrum pode organizar o atendimento e conectar o que acontece depois dele.</p><div className="sy-demo-note"><BrandMark variant="symbol"/><span>Sem números inventados.<br/>Sem demonstração genérica.</span></div></div><CommercialLeadForm/></section>
    <section className="sy-faq"><header><span className="sy-kicker">PERGUNTAS FREQUENTES</span><h2>Antes de começar.</h2></header><div>{faq.map((item,index)=><details key={item[0]} open={index===0}><summary>{item[0]}<span>＋</span></summary><p>{item[1]}</p></details>)}</div></section>
  </main><footer className="sy-footer"><div><BrandMark/><p>A central operacional da sua empresa.</p></div><nav><a href="#plataforma">Plataforma</a><a href="#servicos">Serviços</a><a href="#implantacao">Implantação</a><Link href="https://app.syrum.com.br/login">Entrar</Link></nav><small>© {new Date().getFullYear()} Syrum Tecnologia.</small></footer></div>;
}
